name: Test, build and deploy gitcounter-runner

on:
  push:
    branches:
      - 'master'

env:
  image: docker.pkg.github.com/${{ github.repository }}/gitcounter

jobs:
  build:
    name: Run pytest, then build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Test with pytest
        run: poetry run pytest
      - name: Generate image environment variable
        run: |
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
      - name: Build and push docker image
	if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker build . --tag $IMAGE
          docker push $IMAGE

  deploy:
    name: Deploy to Kubernetes
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate image environment variable
        run: |
          version=$(./version.sh)
          echo "version=${version}" >> $GITHUB_ENV
          echo "IMAGE=${image}:${version}" >> $GITHUB_ENV
          echo "NAIS_YAML=${GITHUB_WORKSPACE}/nais-yaml" >> $GITHUB_ENV
          pwd
      - name: Bump version in nais-yaml
        env:
          DEPLOY_KEY: ${{ secrets.NAIS_YAML_DEPLOY_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${DEPLOY_KEY}"
          mkdir -p $NAIS_YAML
          git clone git@github.com:navikt/nais-yaml.git $NAIS_YAML
          cd $NAIS_YAML
          git config user.email "aura@nav.no"
          git config user.name "NAIS deploy pipeline"
          sed -E -i "s#image: .+#image: ${IMAGE}#" vars/gitcounter-runner.yaml
          git add .
          git --no-pager diff --cached
          git commit -a -m "Bump gitcounter-runner to version ${version}"
          git push
